### ISSUE TITLE
Investigate BMI

### ISSUE THREAD

**Issue by ld-archer** [ld-archer/E_FEM#41]
BMI is a bit of a problem in the current version of the model. 

Firstly, BMI is was only measured and recorded on even waves in ELSA, which means we have NO data for odd waves. On top of that, there is also a considerable proportion of BMI data missing for the even waves, hovering between 40-60% missing (ridiculous). 

To handle the missing data, we first impute BMI for even waves using hotdecking. Then, we interpolate the odd waves using even waves. This already introduces some problems, for example, people who have a low BMI in wave 2 (e.g. 16) and a higher BMI in wave 4 (e.g. 22), the values for wave 1 are impossibly low due to interpolating outside the range of known data. 

Also, after interpolating we add some noise using a normal distribution. We take a sample of a normal distribution with limits (-2, 2), and add this to the interpolated data. We did this in the first place because the lag of bmi was almost a perfect predictor of current, which shouldn't be the case.

**ToDo**

- [x] Check mean of BMI in CV1 stock pop and CV1 transition data
- [x] When looking at the minimal models and comparing to ELSA data (see comment in #35 ) focus on BMI and try to understand the outputs
- [x] Remove RMSE term from BMI model and see what impact this has (do this by directly editing the .est file before simulation, not the code)
