### ISSUE TITLE
Work status

### ISSUE THREAD

**Issue by ld-archer** [ld-archer/E_FEM#57]
Think the best solution to all this would be to tie all the work and unemployment information together into a workstat variable. The labour force status variable `r*lbrf_e` seems a good place to start, here are the categories to that var:
```
Value----------------------|
.d:DK
.o:Other
.r:Refuse
1.employed
2.self-employed
3.unemployed
4.partly ret
5.retired
6.disabled
7.looking after home or fam
```
- Employed
    - 1 Employed
    - 2 Self-employed
    - 4 Partly retired
- Unemployed (but still in labour force)
    - 3 Unemployed
- Not working (retired, disabled, looking after home...) Will probably label this as retired.
    - 5 Retired
    - 6 Disabled
    - 7 Looking after home or family

Going to open this as another issue, then link both of these issues into a pull request for the work and retirement status variables.

_Originally posted by @ld-archer in https://github.com/ld-archer/E_FEM/issues/43#issuecomment-739250946_

**Todo**

- [x] Add labour force status variable into model
    - [x] reshape_long.do
    - [x] ELSA_covariate_definitionsELSA.do
	    - and minimal
    - [x] sample_selections
    - [x] measures_subpop
    - [x] Vars.cpp
	    - Current
	    - Lag
	    - Probability
	    - Dummy vars
    - [x] Vars.h
    - [x] settings spreadsheet (.csv)
    - [x] settings.txt
    - [x] Cross Validation script
- [x] Test and Impute (if necessary)
- [x] Derive and include dummy vars for:
    - [x] working
    - [x] unemployed
    - [x] retired
    - [x] Make sure all these variables are linked to workstat in Vars.cpp
- [x] Do accounting in HealthModule for any changes between these states
- [x] Check against current work, unemp and retired variables
    - [x] Remove old vars
        - [x] work
        - [x] retemp
        - [x] retage
        - [x] unemp

DON'T TRANSITION THE WORKSTAT VAR. Instead estimate transitions for each of the states (careful with the sample selections) and account. The workstat var is only so these variables are linked and therefore cannot occur at the same time.
